name: auto-deploy

on: 
  push: 
    branches: 
      main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - name: Install Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set the configuration 
        run: git config user.email "bouchard.bergeron.antoine@gmail.com" |
          git config user.name "Antoine Bouchard-Bergeron"
      - name: Install dependancies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Build page
        run: npm run build
      - name: Deploy built page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
