name: auto-deploy

on: 
  push: 
    branches: 
      main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install dependancies
        run: pnpm install
      - name: Run tests
        run: pnpm run test
      - name: Build and deploy to gh-pages
        run: pnpm run deploy
      